var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/csr/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0pe6nsb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0gktajc.js")
R.c("server/chunks/ssr/[root-of-the-server]__12u_11.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bd0tfh._.js")
R.c("server/chunks/ssr/_0yd9~52._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_csr_page_actions_0jbfzhx.js")
R.m(91244)
module.exports=R.m(91244).exports
