var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/operations/onshore/[asset]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ahz.y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ns7h09._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0u3sk8n.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tmbvij._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12u_11.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bd0tfh._.js")
R.c("server/chunks/ssr/_0yd9~52._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_operations_onshore_[asset]_page_actions_1281x6a.js")
R.m(6532)
module.exports=R.m(6532).exports
